// gen-shortcodes parses the GitHub emoji JSON API response and generates
// shortcodes_gen.go containing the full builtinShortcodes mapping table.
//
// Usage:
//
//	go run ./cmd/gen-shortcodes [-in emojis.json] [-out shortcodes_gen.go]
//
// The input JSON is a flat object: shortcode-name → image URL.
// Only entries whose URL contains "/unicode/" are included; GitHub-custom
// entries (octocat, shipit, etc.) have no unicode codepoint and are skipped.
//
// Unicode codepoints are encoded in the URL path, e.g.:
//
//	unicode/1f600.png       → U+1F600 (single codepoint)
//	unicode/1f1e6-1f1e8.png → U+1F1E6 U+1F1E8 (multi-codepoint sequence)
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

var reUnicode = regexp.MustCompile(`/unicode/([0-9a-f][0-9a-f-]*)\.png`)

type entry struct {
	shortcode string // ":name:"
	emoji     string // unicode rune sequence
}

func main() {
	in := flag.String("in", "emojis.json", "path to GitHub emoji JSON file")
	out := flag.String("out", "shortcodes_gen.go", "output Go source file")
	flag.Parse()

	data, err := os.ReadFile(*in)
	if err != nil {
		die("read %s: %v", *in, err)
	}

	var raw map[string]string
	if err := json.Unmarshal(data, &raw); err != nil {
		die("parse JSON: %v", err)
	}

	var entries []entry
	skipped := 0
	for name, url := range raw {
		m := reUnicode.FindStringSubmatch(url)
		if m == nil {
			skipped++
			continue
		}
		emoji, err := hexSeqToString(m[1])
		if err != nil {
			fmt.Fprintf(os.Stderr, "warning: skipping %q (%s): %v\n", name, m[1], err)
			skipped++
			continue
		}
		entries = append(entries, entry{shortcode: ":" + name + ":", emoji: emoji})
	}
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].shortcode < entries[j].shortcode
	})

	src := generate(entries)
	formatted, err := format.Source([]byte(src))
	if err != nil {
		// Write unformatted so the user can see what went wrong.
		_ = os.WriteFile(*out, []byte(src), 0644)
		die("gofmt: %v", err)
	}
	if err := os.WriteFile(*out, formatted, 0644); err != nil {
		die("write %s: %v", *out, err)
	}
	fmt.Fprintf(os.Stderr, "wrote %d shortcodes to %s (skipped %d non-unicode)\n",
		len(entries), *out, skipped)
}

// hexSeqToString converts a hyphen-separated sequence of hex codepoints
// (as found in the GitHub emoji URL) to a UTF-8 string.
// Example: "1f1e6-1f1e8" → "🇦🇨"
func hexSeqToString(s string) (string, error) {
	parts := strings.Split(s, "-")
	runes := make([]rune, 0, len(parts))
	for _, p := range parts {
		n, err := strconv.ParseInt(p, 16, 32)
		if err != nil {
			return "", fmt.Errorf("invalid codepoint %q: %w", p, err)
		}
		runes = append(runes, rune(n))
	}
	return string(runes), nil
}

func generate(entries []entry) string {
	var b strings.Builder
	b.WriteString("// Code generated by cmd/gen-shortcodes/main.go; DO NOT EDIT.\n\n")
	b.WriteString("package demoji\n\n")
	b.WriteString("// builtinShortcodes is the full GitHub/Gemoji shortcode → emoji table,\n")
	b.WriteString("// generated from https://api.github.com/emojis\n")
	b.WriteString("//\n")
	b.WriteString("// When converting unicode → shortcode (demoji mode), the first active entry\n")
	b.WriteString("// for each emoji codepoint sequence becomes the canonical shortcode name.\n")
	b.WriteString("var builtinShortcodes = [][2]string{\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "\t{%q, %q},\n", e.shortcode, e.emoji)
	}
	b.WriteString("}\n")
	return b.String()
}

func die(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "gen-shortcodes: "+format+"\n", args...)
	os.Exit(1)
}
